<?php

namespace common\models;

use common\helpers\DateTime;
use common\models\traits\Template;
use \common\models\base\LoadBidDetails as BaseLoadBidDetails;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;

/**
 * This is the model class for table "load_bid_details".
 */
class LoadBidDetails extends BaseLoadBidDetails
{
    use Template;

    /**
     * @var int
     */
    public $_old_charge_code;
    public $_old_price;
    public $_old_unit_count;
    public $_old_unit_measure;
    public $_old_free_units;
    public $_old_notes;

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->_old_charge_code = $this->charge_code;
        $this->_old_price = $this->price;
        $this->_old_unit_count = $this->unit_count;
        $this->_old_unit_measure = $this->unit_measure;
        $this->_old_free_units = $this->free_units;
        $this->_old_notes = $this->notes;
        return true;
    }

    public function behaviors()
    {
        return DateTime::setLocalTimestamp(parent::behaviors());
    }

    public function rules()
    {
        return ArrayHelper::merge(
            parent::rules(),
            [
                array('load_bid_id','unique','message'=>'{attribute}:{value} already exists!'),
            ]
        );
    }

    public function addNote($str)
    {
        $note = new LoadNote();
        $nowDate = DateTime::nowDateYMD();
        $nowTime = DateTime::nowTime();
        $note->created_at = "{$nowDate} {$nowTime}:00";
        $note->load_id = $this->load_bid_id;
        $note->notes = $str;

        $note->save();
    }
}
