<?php

namespace common\models;

use \common\models\base\Log as BaseLog;

use common\models\traits\Template;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "log".
 */
class Log extends BaseLog
{
    use Template;
    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->action_date = date('c', $this->action_date);
        $this->detail = unserialize($this->detail);
    }

    public function behaviors()
    {
        return ArrayHelper::merge(
            parent::behaviors(),
            [
            ]
        );
    }

    public function rules()
    {
        return ArrayHelper::merge(
            parent::rules(),
            [
                # custom validation rules
            ]
        );
    }
}
