<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "carrier".
 *
 * @property integer $id
 * @property string $name
 * @property string $email
 * @property string $phone
 * @property string $number
 * @property string $password
 * @property string $mc
 * @property string $dot
 * @property string $ein
 * @property string $w9
 * @property string $ic
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $aliasModel
 */
abstract class Carrier extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'carrier';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name','email','phone', 'number', 'password', 'mc', 'dot', 'ein', 'w9', 'ic'], 'string', 'max' => 32]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'email' => 'Email',
            'phone' => 'Phone',
            'number' => 'Number',
            'password' => 'Password',
            'mc' => 'Mc',
            'dot' => 'Dot',
            'ein' => 'Ein',
            'w9' => 'W 9',
            'ic' => 'Ic',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \api\models\CarrierQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \api\models\CarrierQuery(get_called_class());
    }


}
