<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "chassis_locations".
 *
 * @property integer $id
 * @property integer $load_id
 * @property integer $chassis_pickup
 * @property integer $chassis_termination
 *
 * @property \common\models\Location $chassisPickup
 * @property \common\models\Location $chassisTermination
 * @property \common\models\Load $load
 * @property string $aliasModel
 */
abstract class Chassis_locations extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'chassis_locations';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['load_id', 'chassis_pickup', 'chassis_termination'], 'default', 'value' => null],
            [['load_id', 'chassis_pickup', 'chassis_termination'], 'integer'],
            [['load_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Load::className(), 'targetAttribute' => ['load_id' => 'id']],
            [['chassis_pickup'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Location::className(), 'targetAttribute' => ['chassis_pickup' => 'id']],
            [['chassis_termination'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Location::className(), 'targetAttribute' => ['chassis_termination' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'load_id' => 'Load ID',
            'chassis_pickup' => 'Chassis Pickup',
            'chassis_termination' => 'Chassis Termination',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChassisPickup()
    {
        return $this->hasOne(\common\models\Location::className(), ['id' => 'chassis_pickup']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChassisTermination()
    {
        return $this->hasOne(\common\models\Location::className(), ['id' => 'chassis_termination']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoad()
    {
        return $this->hasOne(\common\models\Load::className(), ['id' => 'load_id']);
    }




}
