<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "company".
 *
 * @property integer $id
 * @property string $company_name
 * @property string $street_address
 * @property string $city
 * @property string $state
 * @property string $zip_code
 * @property string $country
 * @property string $business_phone
 * @property string $ein
 * @property string $w9_file
 * @property string $w9_mime_type
 * @property string $ic_file
 * @property string $ic_mime_type
 *
 * @property \common\models\Carrier $carrier
 * @property string $aliasModel
 */
abstract class Company extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'company';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['company_name', 'street_address', 'city', 'state', 'zip_code', 'country', 'business_phone'], 'required'],
            [['company_name', 'street_address', 'city', 'state', 'zip_code', 'country', 'business_phone', 'ein'], 'string', 'max' => 32]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'company_name' => 'Company Name',
            'street_address' => 'Street Address',
            'city' => 'City',
            'state' => 'State',
            'zip_code' => 'Zip Code',
            'country' => 'Country',
            'business_phone' => 'Business Phone',
            'ein' => 'Ein',
            'w9_file' => 'W 9 File',
            'w9_mime_type' => 'W 9 Mime Type',
            'ic_file' => 'Ic File',
            'ic_mime_type' => 'Ic Mime Type',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCarrier()
    {
        return $this->hasOne(\common\models\Carrier::className(), ['company_id' => 'id']);
    }




}
