<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "company".
 *
 * @property integer $id
 * @property string $company_name
 * @property string $business_phone
 * @property string $ein
 * @property string $w9_file
 * @property string $w9_mime_type
 * @property string $ic_file
 * @property string $ic_mime_type
 * @property integer $address_id
 * @property string $mc_number
 * @property string $email
 * @property string $receiver_email
 * @property string $billing_email
 * @property string $quickbooks_email
 * @property string $credit_limit
 * @property string $payment_terms
 * @property boolean $is_customer
 * @property boolean $is_port
 * @property boolean $is_consignee
 * @property boolean $is_chassis
 *
 * @property \common\models\Address $address
 * @property \common\models\Carrier $carrier
 * @property \common\models\Load[] $loads
 * @property \common\models\Load[] $loads0
 * @property \common\models\Load[] $loads1
 * @property string $aliasModel
 */
abstract class Company extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'company';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['address_id'], 'required'],
            [['address_id'], 'default', 'value' => null],
            [['address_id'], 'integer'],
            [['is_customer', 'is_port', 'is_consignee', 'is_chassis'], 'boolean'],
            [['company_name', 'business_phone', 'ein', 'w9_mime_type', 'ic_mime_type', 'mc_number', 'email', 'receiver_email', 'billing_email', 'quickbooks_email', 'credit_limit', 'payment_terms'], 'string', 'max' => 32],
//            [['w9_file', 'ic_file'], 'string', 'max' => 55],
            [['address_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Address::className(), 'targetAttribute' => ['address_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'company_name' => 'Company Name',
            'business_phone' => 'Business Phone',
            'ein' => 'Ein',
            'w9_file' => 'W 9 File',
            'w9_mime_type' => 'W 9 Mime Type',
            'ic_file' => 'Ic File',
            'ic_mime_type' => 'Ic Mime Type',
            'address_id' => 'Address ID',
            'mc_number' => 'Mc Number',
            'email' => 'Email',
            'receiver_email' => 'Receiver Email',
            'billing_email' => 'Billing Email',
            'quickbooks_email' => 'Quickbooks Email',
            'credit_limit' => 'Credit Limit',
            'payment_terms' => 'Payment Terms',
            'is_customer' => 'Is Customer',
            'is_port' => 'Is Port',
            'is_consignee' => 'Is Consignee',
            'is_chassis' => 'Is Chassis',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAddress()
    {
        return $this->hasOne(\common\models\Address::className(), ['id' => 'address_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCarrier()
    {
        return $this->hasOne(\common\models\Carrier::className(), ['company_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoads()
    {
        return $this->hasMany(\common\models\Load::className(), ['customer_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoads0()
    {
        return $this->hasMany(\common\models\Load::className(), ['port_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoads1()
    {
        return $this->hasMany(\common\models\Load::className(), ['consignee_id' => 'id']);
    }




}