<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "consignee".
 *
 * @property integer $id
 * @property string $consignee
 * @property string $delivery_up_from
 * @property string $delivery_up_to
 *
 * @property \common\models\Load[] $loads
 * @property string $aliasModel
 */
abstract class Consignee extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'consignee';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['consignee', 'delivery_up_from', 'delivery_up_to'], 'required'],
            [['consignee', 'delivery_up_from', 'delivery_up_to'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'consignee' => 'Consignee',
            'delivery_up_from' => 'Delivery Up From',
            'delivery_up_to' => 'Delivery Up To',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoads()
    {
        return $this->hasMany(\common\models\Load::className(), ['consignee_id' => 'id']);
    }




}
