<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "container_return".
 *
 * @property integer $id
 * @property integer $load_id
 * @property integer $container_return
 * @property string $return_from
 * @property string $return_to
 *
 * @property \common\models\Location $containerReturn
 * @property \common\models\Load $load
 * @property string $aliasModel
 */
abstract class Container_return extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'container_return';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['load_id', 'container_return'], 'default', 'value' => null],
            [['load_id', 'container_return'], 'integer'],
            [['return_from', 'return_to'], 'safe'],
            [['load_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Load::className(), 'targetAttribute' => ['load_id' => 'id']],
            [['container_return'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Location::className(), 'targetAttribute' => ['container_return' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'load_id' => 'Load ID',
            'container_return' => 'Container Return',
            'return_from' => 'Return From',
            'return_to' => 'Return To',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContainerReturn()
    {
        return $this->hasOne(\common\models\Location::className(), ['id' => 'container_return']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoad()
    {
        return $this->hasOne(\common\models\Load::className(), ['id' => 'load_id']);
    }




}
