<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "container_bid_log".
 *
 * @property integer $id
 * @property integer $container_bid_id
 * @property integer $log_id
 *
 * @property \common\models\ContainerBid $containerBid
 * @property \common\models\Log $log
 * @property string $aliasModel
 */
abstract class ContainerBidLog extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'container_bid_log';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['container_bid_id', 'log_id'], 'default', 'value' => null],
            [['container_bid_id', 'log_id'], 'integer'],
            [['container_bid_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\ContainerBid::className(), 'targetAttribute' => ['container_bid_id' => 'id']],
            [['log_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Log::className(), 'targetAttribute' => ['log_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'container_bid_id' => 'Container Bid ID',
            'log_id' => 'Log ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContainerBid()
    {
        return $this->hasOne(\common\models\ContainerBid::className(), ['id' => 'container_bid_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLog()
    {
        return $this->hasOne(\common\models\Log::className(), ['id' => 'log_id']);
    }




}
