<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "container_bid_detail".
 *
 * @property integer $id
 * @property integer $container_bid_id
 * @property integer $charge_id
 * @property integer $measure_id
 * @property string $price
 * @property string $free_unit
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property \common\models\Charge $charge
 * @property \common\models\ContainerBid $containerBid
 * @property \common\models\Measure $measure
 * @property string $aliasModel
 */
abstract class ContainerBidDetail extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'container_bid_detail';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['container_bid_id', 'charge_id'], 'required'],
            [['container_bid_id', 'charge_id', 'measure_id'], 'default', 'value' => null],
            [['container_bid_id'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'container_bid_id' => 'Container Bid ID',
            'charge_id' => 'Charge ID',
            'measure_id' => 'Measure ID',
            'price' => 'Price',
            'free_unit' => 'Free Unit',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCharge()
    {
        return $this->hasOne(\common\models\Charge::className(), ['id' => 'charge_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContainerBid()
    {
        return $this->hasOne(\common\models\ContainerBid::className(), ['id' => 'container_bid_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMeasure()
    {
        return $this->hasOne(\common\models\Measure::className(), ['id' => 'measure_id']);
    }

}
