<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use common\enums\UserRole;
use common\models\User;
use common\models\ContainerBidDetail;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "container_bid".
 *
 * @property integer $id
 * @property string $is_favorite
 * @property integer $listing_container_id
 * @property integer $quantity
 * @property string $note
 * @property integer $edit_counting
 * @property integer $user_id
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property \common\models\ListingContainer $listingContainer
 * @property User $user
 * @property ContainerBidDetail[] $containerBidDetail
 * @property string $aliasModel
 */
abstract class ContainerBid extends \yii\db\ActiveRecord
{
    public $role = UserRole::CARRIER;


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'container_bid';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['id', 'integer'],
            [['listing_container_id', 'user_id'], 'required'],
            [['is_favorite'], 'default', 'value' => false],
            [['listing_container_id', 'quantity', 'edit_counting', 'user_id'], 'default', 'value' => null],
            [['listing_container_id', 'quantity', 'edit_counting', 'user_id'], 'integer'],
            [['note'], 'string', 'max' => 255],
            [['listing_container_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\ListingContainer::className(), 'targetAttribute' => ['listing_container_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id', 'role' => 'role']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'is_favorite' => 'Is Favorite',
            'listing_container_id' => 'Listing Container ID',
            'quantity' => 'Quantity',
            'note' => 'Note',
            'edit_counting' => 'Edit Counting',
            'user_id' => 'User ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getListingContainer()
    {
        return $this->hasOne(\common\models\ListingContainer::className(), ['id' => 'listing_container_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContainerBidDetail(): \yii\db\ActiveQuery
    {
        return $this->hasMany(ContainerBidDetail::class, ['container_bid_id' => 'id']);
    }


}
