<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "customer".
 *
 * @property integer $id
 * @property integer $company_id
 * @property integer $contact_info_id
 * @property string $type
 * @property string $contact_name
 * @property string $job_title
 *
 * @property \common\models\Company $company
 * @property \common\models\ContactInfo $contactInfo
 * @property string $aliasModel
 */
abstract class Customer extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'customer';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type','company_id', 'contact_name','contact_info_id'], 'required'],
            [['company_id', 'contact_info_id'], 'integer'],
            [['type', 'contact_name', 'job_title'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany(): \yii\db\ActiveQuery
    {
        return $this->hasOne(\common\models\Company::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContactInfo(): \yii\db\ActiveQuery
    {
        return $this->hasOne(\common\models\ContactInfo::className(), ['id' => 'contact_info_id']);
    }

}
