<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "holds".
 *
 * @property integer $id
 * @property integer $load_id
 * @property string $freight_hold
 * @property string $customer_hold
 * @property string $carrier_hold
 * @property string $broker_hold
 *
 * @property \common\models\Load $load
 * @property string $aliasModel
 */
abstract class Holds extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'holds';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['load_id'], 'default', 'value' => null],
            [['load_id'], 'integer'],
            [['freight_hold', 'customer_hold', 'carrier_hold', 'broker_hold'], 'string', 'max' => 255],
            [['load_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Load::className(), 'targetAttribute' => ['load_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'load_id' => 'Load ID',
            'freight_hold' => 'Freight Hold',
            'customer_hold' => 'Customer Hold',
            'carrier_hold' => 'Carrier Hold',
            'broker_hold' => 'Broker Hold',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoad()
    {
        return $this->hasOne(\common\models\Load::className(), ['id' => 'load_id']);
    }




}
