<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "listing_ordinary_description".
 *
 * @property integer $id
 * @property integer $listing_ordinary_id
 * @property integer $quantity
 * @property string $size
 * @property integer $weight
 *
 * @property \common\models\ListingOrdinary $listingOrdinary
 * @property string $aliasModel
 */
abstract class ListingOrdinaryInfo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'listing_ordinary_info';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['listing_ordinary_id', 'quantity', 'weight'], 'default', 'value' => null],
            [['listing_ordinary_id', 'quantity', 'weight'], 'integer'],
            [['size'], 'string', 'max' => 255],
            [['listing_ordinary_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\ListingOrdinary::className(), 'targetAttribute' => ['listing_ordinary_id' => 'id']],
            [['listing_ordinary_id'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'listing_ordinary_id' => 'Listing Ordinary ID',
            'quantity' => 'Quantity',
            'size' => 'Size',
            'weight' => 'Weight',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getListingOrdinary(): \yii\db\ActiveQuery
    {
        return $this->hasOne(\common\models\ListingOrdinary::className(), ['id' => 'listing_ordinary_id']);
    }

}
