<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "listing_ordinary_additional_info".
 *
 * @property integer $id
 * @property integer $listing_ordinary_id
 * @property string $hazmat_description
 * @property string $overweight_description
 * @property string $reefer_description
 * @property string $alcohol_description
 * @property string $urgent_description
 * @property string $note
 *
 * @property \common\models\ListingOrdinary $listingOrdinary
 * @property string $aliasModel
 */
abstract class ListingOrdinaryAdditionalInfo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'listing_ordinary_additional_info';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['note'], 'default', 'value' => null],
            [['listing_ordinary_id'], 'required'],
            [['listing_ordinary_id'], 'integer'],
            [['hazmat_description', 'overweight_description', 'reefer_description', 'alcohol_description', 'urgent_description', 'note'], 'string', 'max' => 255],
            [['listing_ordinary_id'], 'exist', 'targetClass' => \common\models\ListingOrdinary::className(), 'targetAttribute' => ['listing_ordinary_id' => 'id']],
            [['listing_ordinary_id'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'listing_ordinary_id' => 'Listing Ordinary ID',
            'hazmat_description' => 'Hazmat Description',
            'overweight_description' => 'Overweight Description',
            'reefer_description' => 'Reefer Description',
            'alcohol_description' => 'Alcohol Description',
            'urgent_description' => 'Urgent Description',
            'note' => 'Note',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getListingOrdinary()
    {
        return $this->hasOne(\common\models\ListingOrdinary::className(), ['id' => 'listing_ordinary_id']);
    }




}
