<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "listing_container_additional_info".
 *
 * @property integer $id
 * @property integer $listing_container_id
 * @property string $hazmat_description
 * @property string $overweight_description
 * @property string $reefer_description
 * @property string $alcohol_description
 * @property string $urgent_description
 * @property string $note
 *
 * @property \common\models\ListingContainer $listingContainer
 * @property string $aliasModel
 */
abstract class ListingContainerAdditionalInfo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'listing_container_additional_info';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['listing_container_id'], 'required'],
            [['listing_container_id', 'note'], 'default', 'value' => null],
            [['listing_container_id'], 'integer'],
            [['hazmat_description', 'overweight_description', 'reefer_description', 'alcohol_description', 'urgent_description', 'note'], 'string', 'max' => 255],
            [['listing_container_id'], 'unique'],
            [['listing_container_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\ListingContainer::className(), 'targetAttribute' => ['listing_container_id' => 'id']],
            ['note', 'default', 'value' => null]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'listing_container_id' => 'Listing Container ID',
            'hazmat_description' => 'Hazmat Description',
            'overweight_description' => 'Overweight Description',
            'reefer_description' => 'Reefer Description',
            'alcohol_description' => 'Alcohol Description',
            'urgent_description' => 'Urgent Description',
            'note' => 'Note',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getListingContainer()
    {
        return $this->hasOne(\common\models\ListingContainer::className(), ['id' => 'listing_container_id']);
    }




}
