<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use common\models\User;
use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "listing_ordinary".
 *
 * @property integer $id
 * @property string $status
 * @property integer $origin_id
 * @property integer $destination_id
 * @property integer $user_id
 * @property string $pick_up
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property \common\models\Location $destination
 * @property \common\models\ListingOrdinaryAdditionalInfo $additionalInfo
 * @property \common\models\ListingOrdinaryInfo $ordinaryInfo
 * @property \common\models\OrdinaryEquipment[] $ordinaryEquipments
 * @property \common\models\Location $origin
 * @property User $user
 * @property string $aliasModel
 */
abstract class ListingOrdinary extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'listing_ordinary';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['origin_id', 'destination_id'], 'default', 'value' => null],
            [['origin_id', 'destination_id', 'user_id'], 'integer'],
            [['pick_up'], 'safe'],
            [['status'], 'string', 'max' => 255],
            [['origin_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Location::className(), 'targetAttribute' => ['origin_id' => 'id']],
            [['destination_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Location::className(), 'targetAttribute' => ['destination_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'status' => 'Status',
            'origin_id' => 'Origin ID',
            'destination_id' => 'Destination ID',
            'pick_up' => 'Pick Up',
            'user_id' => 'User ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDestination()
    {
        return $this->hasOne(\common\models\Location::className(), ['id' => 'destination_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAdditionalInfo()
    {
        return $this->hasOne(\common\models\ListingOrdinaryAdditionalInfo::className(), ['listing_ordinary_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrdinaryEquipments()
    {
        return $this->hasMany(\common\models\OrdinaryEquipment::className(), ['listing_ordinary_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrigin()
    {
        return $this->hasOne(\common\models\Location::className(), ['id' => 'origin_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrdinaryInfo()
    {
        return $this->hasOne(\common\models\ListingOrdinaryInfo::className(), ['listing_ordinary_id' => 'id']);
    }

}
