<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "load_ordinary_description".
 *
 * @property integer $id
 * @property integer $load_id
 * @property integer $pallets
 * @property string $weight_LBs
 * @property string $pallet_size
 *
 * @property \common\models\OrdinaryLoad $load
 * @property \common\models\LoadOrdinaryDescriptionRows[] $loadOrdinaryDescriptionRows
 * @property string $aliasModel
 */
abstract class LoadOrdinaryDescription extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'load_ordinary_description';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['load_id', 'pallets'], 'default', 'value' => null],
            [['load_id', 'pallets'], 'integer'],
            [['weight_LBs'], 'number'],
            [['pallet_size'], 'string', 'max' => 255],
            [['load_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\OrdinaryLoad::className(), 'targetAttribute' => ['load_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'load_id' => 'Load ID',
            'pallets' => 'Pallets',
            'weight_LBs' => 'Weight L Bs',
            'pallet_size' => 'Pallet Size',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoad()
    {
        return $this->hasOne(\common\models\OrdinaryLoad::className(), ['id' => 'load_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadOrdinaryDescriptionRows()
    {
        return $this->hasMany(\common\models\LoadOrdinaryDescriptionRows::className(), ['load_ordinary_description_id' => 'id']);
    }




}
