<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "load".
 *
 * @property integer $id
 * @property integer $customer_id
 * @property integer $port_id
 * @property integer $consignee_id
 * @property string $vessel_eta
 * @property string $broker_name
 * @property integer $load_status
 *
 * @property \common\models\Company $consignee
 * @property \common\models\Company $customer
 * @property \common\models\LoadBid[] $loadBs
 * @property \common\models\LoadDocuments[] $loadDocuments
 * @property \common\models\LoadStatus $loadStatus
 * @property \common\models\LoadStop[] $loadStops
 * @property \common\models\LoadStop[] $loadStops0
 * @property \common\models\LoadTracking[] $loadTrackings
 * @property \common\models\Company $port
 * @property string $aliasModel
 */
abstract class Load extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'load';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['customer_id', 'port_id', 'consignee_id'], 'required'],
            [['customer_id', 'port_id', 'consignee_id', 'load_status'], 'default', 'value' => null],
            [['customer_id', 'port_id', 'consignee_id', 'load_status'], 'integer'],
            [['vessel_eta'], 'safe'],
            [['broker_name'], 'string', 'max' => 32],
            [['customer_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Company::className(), 'targetAttribute' => ['customer_id' => 'id']],
            [['port_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Company::className(), 'targetAttribute' => ['port_id' => 'id']],
            [['consignee_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Company::className(), 'targetAttribute' => ['consignee_id' => 'id']],
            [['load_status'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\LoadStatus::className(), 'targetAttribute' => ['load_status' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'customer_id' => 'Customer ID',
            'port_id' => 'Port ID',
            'consignee_id' => 'Consignee ID',
            'vessel_eta' => 'Vessel Eta',
            'broker_name' => 'Broker Name',
            'load_status' => 'Load Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConsignee()
    {
        return $this->hasOne(\common\models\Company::className(), ['id' => 'consignee_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(\common\models\Company::className(), ['id' => 'customer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadBs()
    {
        return $this->hasMany(\common\models\LoadBid::className(), ['load_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadDocuments()
    {
        return $this->hasMany(\common\models\LoadDocuments::className(), ['load_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadStatus()
    {
        return $this->hasOne(\common\models\LoadStatus::className(), ['id' => 'load_status']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadStops()
    {
        return $this->hasMany(\common\models\LoadStop::className(), ['port_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadStops0()
    {
        return $this->hasMany(\common\models\LoadStop::className(), ['company_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadTrackings()
    {
        return $this->hasMany(\common\models\LoadTracking::className(), ['load_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPort()
    {
        return $this->hasOne(\common\models\Company::className(), ['id' => 'port_id']);
    }




}
