<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "load_bid_details".
 *
 * @property integer $id
 * @property integer $load_bid_id
 * @property integer $charge_code
 * @property string $price
 * @property string $unit_measure
 * @property string $free_units
 * @property string $note_from_carrier
 * @property integer $edit_bid_details
 *
 * @property \common\models\LoadBid $loadBid
 * @property string $aliasModel
 */
abstract class LoadBidDetails extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'load_bid_details';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['load_bid_id', 'unit_measure'], 'required'],
            [['load_bid_id', 'charge_code', 'edit_bid_details'], 'default', 'value' => null],
            [['load_bid_id', 'charge_code', 'edit_bid_details'], 'integer'],
            [['price', 'free_units'], 'number'],
            [['note_from_carrier'], 'string'],
            [['unit_measure'], 'string', 'max' => 32],
            [['load_bid_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\LoadBid::className(), 'targetAttribute' => ['load_bid_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'load_bid_id' => 'Load Bid ID',
            'charge_code' => 'Charge Code',
            'price' => 'Price',
            'unit_measure' => 'Unit Measure',
            'free_units' => 'Free Units',
            'note_from_carrier' => 'Note From Carrier',
            'edit_bid_details' => 'Edit Bid Details',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadBid()
    {
        return $this->hasOne(\common\models\LoadBid::className(), ['id' => 'load_bid_id']);
    }




}
