<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "load_ordinary_additional_info".
 *
 * @property integer $id
 * @property integer $load_id
 * @property string $hazmat
 * @property string $hazmat_description
 * @property string $overweight
 * @property string $overweight_description
 * @property string $reefer
 * @property string $reefer_description
 * @property string $alcohol
 * @property string $alcohol_description
 * @property string $urgent
 * @property string $urgent_description
 * @property string $note
 * @property integer $weight_in_LBs
 *
 * @property \common\models\OrdinaryLoad $load
 * @property string $aliasModel
 */
abstract class LoadOrdinaryAdditionalInfo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'load_ordinary_additional_info';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['load_id', 'weight_in_LBs'], 'default', 'value' => null],
            [['load_id', 'weight_in_LBs'], 'integer'],
            [['note'], 'string'],
            [['hazmat', 'hazmat_description', 'overweight', 'overweight_description', 'reefer', 'reefer_description', 'alcohol', 'alcohol_description', 'urgent', 'urgent_description'], 'string', 'max' => 255],
            [['load_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\OrdinaryLoad::className(), 'targetAttribute' => ['load_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'load_id' => 'Load ID',
            'hazmat' => 'Hazmat',
            'hazmat_description' => 'Hazmat Description',
            'overweight' => 'Overweight',
            'overweight_description' => 'Overweight Description',
            'reefer' => 'Reefer',
            'reefer_description' => 'Reefer Description',
            'alcohol' => 'Alcohol',
            'alcohol_description' => 'Alcohol Description',
            'urgent' => 'Urgent',
            'urgent_description' => 'Urgent Description',
            'note' => 'Note',
            'weight_in_LBs' => 'Weight In L Bs',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoad()
    {
        return $this->hasOne(\common\models\OrdinaryLoad::className(), ['id' => 'load_id']);
    }




}
