<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "load_additional_info".
 *
 * @property integer $id
 * @property integer $load_id
 * @property string $hazmat
 * @property string $overweight
 * @property string $reefer
 * @property string $alcohol
 * @property string $urgent
 * @property string $note_from_broker
 * @property string $hazmat_description
 * @property string $weight_in_lbs
 * @property string $temp_in_f
 * @property string $alcohol_description
 * @property string $urgent_description
 *
 * @property \common\models\Load $load
 * @property string $aliasModel
 */
abstract class LoadAdditionalInfo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'load_additional_info';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['load_id'], 'default', 'value' => null],
            [['load_id'], 'integer'],
            [['note_from_broker'], 'string'],
            [['hazmat', 'overweight'], 'string', 'max' => 132],
            [['reefer', 'alcohol', 'urgent'], 'string', 'max' => 32],
            [['hazmat_description', 'weight_in_lbs', 'temp_in_f', 'alcohol_description', 'urgent_description'], 'string', 'max' => 255],
            [['load_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Load::className(), 'targetAttribute' => ['load_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'load_id' => 'Load ID',
            'hazmat' => 'Hazmat',
            'overweight' => 'Overweight',
            'reefer' => 'Reefer',
            'alcohol' => 'Alcohol',
            'urgent' => 'Urgent',
            'note_from_broker' => 'Note From Broker',
            'hazmat_description' => 'Hazmat Description',
            'weight_in_lbs' => 'Weight In Lbs',
            'temp_in_f' => 'Temp In F',
            'alcohol_description' => 'Alcohol Description',
            'urgent_description' => 'Urgent Description',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoad()
    {
        return $this->hasOne(\common\models\Load::className(), ['id' => 'load_id']);
    }




}
