<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "load_bid".
 *
 * @property integer $id
 * @property integer $load_id
 * @property integer $carrier_id
 * @property string $date
 *
 * @property \common\models\Load $load
 * @property \common\models\LoadBidDetails[] $loadBidDetails
 * @property string $aliasModel
 */
abstract class LoadBid extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'load_bid';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['load_id', 'carrier_id'], 'default', 'value' => null],
            [['load_id', 'carrier_id'], 'integer'],
            [['date'], 'safe'],
            [['load_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Load::className(), 'targetAttribute' => ['load_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'load_id' => 'Load ID',
            'carrier_id' => 'Carrier ID',
            'date' => 'Date',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoad()
    {
        return $this->hasOne(\common\models\Load::className(), ['id' => 'load_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadBidDetails()
    {
        return $this->hasMany(\common\models\LoadBidDetails::className(), ['load_bid_id' => 'id']);
    }




}
