<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "load_stop".
 *
 * @property integer $id
 * @property integer $port_id
 * @property string $stop_type
 * @property integer $company_id
 * @property string $from
 * @property string $to
 *
 * @property \common\models\Load $company
 * @property \common\models\Load $port
 * @property string $aliasModel
 */
abstract class LoadStop extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'load_stop';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['port_id', 'company_id'], 'required'],
            [['port_id', 'company_id'], 'default', 'value' => null],
            [['port_id', 'company_id'], 'integer'],
            [['from', 'to'], 'safe'],
            [['stop_type'], 'string', 'max' => 32],
            [['port_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Load::className(), 'targetAttribute' => ['port_id' => 'id']],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Load::className(), 'targetAttribute' => ['company_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'port_id' => 'Port ID',
            'stop_type' => 'Stop Type',
            'company_id' => 'Company ID',
            'from' => 'From',
            'to' => 'To',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\common\models\Load::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPort()
    {
        return $this->hasOne(\common\models\Load::className(), ['id' => 'port_id']);
    }




}