<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "load_ordinary_reference_number".
 *
 * @property integer $id
 * @property integer $load_id
 * @property string $seal
 * @property string $pick_up
 * @property string $appointment
 * @property string $reservation
 *
 * @property \common\models\Load $load
 * @property string $aliasModel
 */
abstract class LoadOrdinaryReferenceNumber extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'load_ordinary_reference_number';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['load_id'], 'required'],
            [['load_id'], 'default', 'value' => null],
            [['load_id'], 'integer'],
            [['seal', 'pick_up', 'appointment', 'reservation'], 'string', 'max' => 32],
            [['load_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Load::className(), 'targetAttribute' => ['load_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'load_id' => 'Load ID',
            'seal' => 'Seal',
            'pick_up' => 'Pick Up',
            'appointment' => 'Appointment',
            'reservation' => 'Reservation',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoad()
    {
        return $this->hasOne(\common\models\Load::className(), ['id' => 'load_id']);
    }




}
