<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "load_container_info".
 *
 * @property integer $id
 * @property integer $load_id
 * @property integer $number
 * @property string $size
 * @property string $type
 * @property integer $owner
 * @property string $vessel_name
 * @property string $mbl
 * @property string $hbl
 *
 * @property \common\models\Load $load
 * @property \common\models\Owner $owner0
 * @property string $aliasModel
 */
abstract class LoadContainerInfo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'load_container_info';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['load_id', 'number', 'owner'], 'default', 'value' => null],
            [['load_id', 'number', 'owner'], 'integer'],
            [['size', 'type', 'vessel_name', 'mbl', 'hbl'], 'string', 'max' => 32],
            [['load_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Load::className(), 'targetAttribute' => ['load_id' => 'id']],
            [['owner'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Owner::className(), 'targetAttribute' => ['owner' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'load_id' => 'Load ID',
            'number' => 'Number',
            'size' => 'Size',
            'type' => 'Type',
            'owner' => 'Owner',
            'vessel_name' => 'Vessel Name',
            'mbl' => 'Mbl',
            'hbl' => 'Hbl',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoad()
    {
        return $this->hasOne(\common\models\Load::className(), ['id' => 'load_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOwner0()
    {
        return $this->hasOne(\common\models\Owner::className(), ['id' => 'owner']);
    }




}
