<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "load_container_info".
 *
 * @property integer $id
 * @property integer $load_id
 * @property string $type
 * @property integer $container_number
 * @property integer $size
 * @property integer $owner_id
 * @property string $chassis
 * @property string $chassis_type
 * @property integer $chassis_size
 * @property integer $chassis_owner_id
 * @property string $chassis_genset
 *
 * @property \common\models\Owner $chassisOwner
 * @property \common\models\Container $chassisType
 * @property \common\models\Load $load
 * @property \common\models\LoadReferenceNumber $loadReferenceNumbers
 * @property \common\models\Owner $owner
 * @property \common\models\Container $type0
 * @property string $aliasModel
 */
abstract class LoadContainerInfo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'load_container_info';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['load_id', 'container_number', 'size', 'owner_id', 'chassis_size', 'chassis_owner_id'], 'default', 'value' => null],
            [['load_id', 'container_number', 'size', 'owner_id', 'chassis_size', 'chassis_owner_id'], 'integer'],
            [['type', 'chassis', 'chassis_type', 'chassis_genset'], 'string', 'max' => 32],
            [['type'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Container::className(), 'targetAttribute' => ['type' => 'code']],
            [['chassis_type'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Container::className(), 'targetAttribute' => ['chassis_type' => 'code']],
            [['load_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Load::className(), 'targetAttribute' => ['load_id' => 'id']],
            [['owner_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Owner::className(), 'targetAttribute' => ['owner_id' => 'id']],
            [['chassis_owner_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Owner::className(), 'targetAttribute' => ['chassis_owner_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'load_id' => 'Load ID',
            'type' => 'Type',
            'container_number' => 'Container Number',
            'size' => 'Size',
            'owner_id' => 'Owner ID',
            'chassis' => 'Chassis',
            'chassis_type' => 'Chassis Type',
            'chassis_size' => 'Chassis Size',
            'chassis_owner_id' => 'Chassis Owner ID',
            'chassis_genset' => 'Chassis Genset',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChassisOwner()
    {
        return $this->hasOne(\common\models\Owner::className(), ['id' => 'chassis_owner_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChassisType()
    {
        return $this->hasOne(\common\models\Container::className(), ['code' => 'chassis_type']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoad()
    {
        return $this->hasOne(\common\models\Load::className(), ['id' => 'load_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadReferenceNumbers()
    {
        return $this->hasOne(\common\models\LoadReferenceNumber::className(), ['load_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOwner()
    {
        return $this->hasOne(\common\models\Owner::className(), ['id' => 'owner_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getType0()
    {
        return $this->hasOne(\common\models\Container::className(), ['code' => 'type']);
    }




}
