<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "load_note".
 *
 * @property integer $id
 * @property integer $load_id
 * @property string $note_from_carrier
 * @property integer $created_by
 * @property string $created_at
 *
 * @property \common\models\User $createdBy
 * @property \common\models\LoadBid $load
 * @property string $aliasModel
 */
abstract class LoadNote extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'load_note';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'updatedByAttribute' => false,
            ],
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['load_id'], 'required'],
            [['load_id'], 'default', 'value' => null],
            [['load_id'], 'integer'],
            [['note_from_carrier'], 'string'],
            [['load_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\LoadBid::className(), 'targetAttribute' => ['load_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['created_by' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'load_id' => 'Load ID',
            'created_by' => 'Created By',
            'created_at' => 'Created At',
            'note_from_carrier' => 'Note From Carrier',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoad()
    {
        return $this->hasOne(\common\models\LoadBid::className(), ['id' => 'load_id']);
    }




}
