<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "log".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $action_id
 * @property integer $action_date
 * @property string $detail
 *
 * @property \common\models\User $user
 * @property string $aliasModel
 */
abstract class Log extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'log';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'action_id', 'action_date'], 'default', 'value' => null],
            [['user_id', 'action_id', 'action_date'], 'integer'],
            [['action_date', 'detail'], 'required'],
            [['detail'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'action_id' => 'Action ID',
            'action_date' => 'Action Date',
            'detail' => 'Detail',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'user_id']);
    }




}
