<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "ordinary_load".
 *
 * @property integer $id
 * @property integer $customer_id
 * @property integer $origin
 * @property integer $destination
 * @property integer $equipment_need
 * @property string $pick_up_date
 *
 * @property \common\models\Company $customer
 * @property \common\models\Location $destination0
 * @property \common\models\OrdinaryNeeded $equipmentNeed
 * @property \common\models\Location $origin0
 * @property string $aliasModel
 */
abstract class OrdinaryLoad extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ordinary_load';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['customer_id', 'origin', 'destination', 'equipment_need'], 'default', 'value' => null],
            [['customer_id', 'origin', 'destination', 'equipment_need'], 'integer'],
            [['pick_up_date'], 'safe'],
            [['customer_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Company::className(), 'targetAttribute' => ['customer_id' => 'id']],
            [['origin'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Location::className(), 'targetAttribute' => ['origin' => 'id']],
            [['destination'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Location::className(), 'targetAttribute' => ['destination' => 'id']],
            [['equipment_need'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\OrdinaryNeeded::className(), 'targetAttribute' => ['equipment_need' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'customer_id' => 'Customer ID',
            'origin' => 'Origin',
            'destination' => 'Destination',
            'equipment_need' => 'Equipment Need',
            'pick_up_date' => 'Pick Up Date',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(\common\models\Company::className(), ['id' => 'customer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDestination0()
    {
        return $this->hasOne(\common\models\Location::className(), ['id' => 'destination']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEquipmentNeed()
    {
        return $this->hasOne(\common\models\OrdinaryNeeded::className(), ['id' => 'equipment_need']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrigin0()
    {
        return $this->hasOne(\common\models\Location::className(), ['id' => 'origin']);
    }




}
