<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "ordinary_equipment".
 *
 * @property integer $id
 * @property integer $listing_ordinary_id
 * @property string $equipment_code
 *
 * @property \common\models\Equipment $equipmentCode
 * @property \common\models\ListingOrdinary $listingOrdinary
 * @property string $aliasModel
 */
abstract class OrdinaryEquipment extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ordinary_equipment';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['listing_ordinary_id'], 'default', 'value' => null],
            [['listing_ordinary_id'], 'integer'],
            [['equipment_code'], 'string', 'max' => 255],
            [['equipment_code'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Equipment::className(), 'targetAttribute' => ['equipment_code' => 'code']],
            [['listing_ordinary_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\ListingOrdinary::className(), 'targetAttribute' => ['listing_ordinary_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'listing_ordinary_id' => 'Listing Ordinary ID',
            'equipment_code' => 'Equipment Code',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEquipmentCode()
    {
        return $this->hasOne(\common\models\Equipment::className(), ['code' => 'equipment_code']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getListingOrdinary()
    {
        return $this->hasOne(\common\models\ListingOrdinary::className(), ['id' => 'listing_ordinary_id']);
    }




}
