<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "ordinary_needed".
 *
 * @property integer $id
 * @property string $ordinary_need
 * @property integer $equipment_needed_id
 *
 * @property \common\models\OrdinaryLoad $equipmentNeeded
 * @property string $aliasModel
 */
abstract class OrdinaryNeeded extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ordinary_needed';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['equipment_needed_id'], 'default', 'value' => null],
            [['equipment_needed_id'], 'integer'],
            [['ordinary_need'], 'string', 'max' => 255],
            [['equipment_needed_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\OrdinaryLoad::className(), 'targetAttribute' => ['equipment_needed_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ordinary_need' => 'Ordinary Need',
            'equipment_needed_id' => 'Equipment Needed ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEquipmentNeeded()
    {
        return $this->hasOne(\common\models\OrdinaryLoad::className(), ['id' => 'equipment_needed_id']);
    }




}
