<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "ordinary_bid_log".
 *
 * @property integer $id
 * @property integer $ordinary_bid_id
 * @property integer $log_id
 *
 * @property \common\models\Log $log
 * @property \common\models\OrdinaryBid $ordinaryBid
 * @property string $aliasModel
 */
abstract class OrdinaryBidLog extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ordinary_bid_log';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ordinary_bid_id', 'log_id'], 'default', 'value' => null],
            [['ordinary_bid_id', 'log_id'], 'integer'],
            [['log_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Log::className(), 'targetAttribute' => ['log_id' => 'id']],
            [['ordinary_bid_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\OrdinaryBid::className(), 'targetAttribute' => ['ordinary_bid_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ordinary_bid_id' => 'Ordinary Bid ID',
            'log_id' => 'Log ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLog()
    {
        return $this->hasOne(\common\models\Log::className(), ['id' => 'log_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrdinaryBid()
    {
        return $this->hasOne(\common\models\OrdinaryBid::className(), ['id' => 'ordinary_bid_id']);
    }




}
