<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;


/**
 * This is the base-model class for table "ordinary_bid_detail".
 *
 * @property integer $id
 * @property integer $ordinary_bid_id
 * @property integer $charge_id
 * @property integer $measure_id
 * @property string $price
 * @property integer $free_unit
 *
 * @property \common\models\Charge $charge
 * @property \common\models\Measure $measure
 * @property \common\models\OrdinaryBid $ordinaryBid
 * @property string $aliasModel
 */
abstract class OrdinaryBidDetail extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ordinary_bid_detail';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ordinary_bid_id', 'charge_id', 'measure_id', 'price'], 'required'],
            [['ordinary_bid_id', 'charge_id', 'measure_id', 'free_unit'], 'default', 'value' => null],
            [['ordinary_bid_id'], 'integer'],

        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ordinary_bid_id' => 'Ordinary Bid ID',
            'charge_id' => 'Charge ID',
            'measure_id' => 'Measure ID',
            'price' => 'Price',
            'free_unit' => 'Free Unit',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCharge()
    {
        return $this->hasOne(\common\models\Charge::className(), ['id' => 'charge_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMeasure()
    {
        return $this->hasOne(\common\models\Measure::className(), ['id' => 'measure_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrdinaryBid()
    {
        return $this->hasOne(\common\models\OrdinaryBid::className(), ['id' => 'ordinary_bid_id']);
    }




}
