<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "owner".
 *
 * @property integer $id
 * @property string $name
 *
 * @property \common\models\ListingContainerInfo[] $listingContainerInfos
 * @property \common\models\LoadContainerInfo[] $loadContainerInfos
 * @property \common\models\LoadContainerInfo[] $loadContainerInfos0
 * @property string $aliasModel
 */
abstract class Owner extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'owner';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 32]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getListingContainerInfos()
    {
        return $this->hasMany(\common\models\ListingContainerInfo::className(), ['owner_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadContainerInfos()
    {
        return $this->hasMany(\common\models\LoadContainerInfo::className(), ['owner_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadContainerInfos0()
    {
        return $this->hasMany(\common\models\LoadContainerInfo::className(), ['chassis_owner_id' => 'id']);
    }




}
