<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "port".
 *
 * @property integer $id
 * @property string $port
 * @property string $pick_up_from
 * @property string $pick_up_to
 *
 * @property \common\models\Load[] $loads
 * @property string $aliasModel
 */
abstract class Port extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'port';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['port', 'pick_up_from', 'pick_up_to'], 'required'],
            [['port', 'pick_up_from', 'pick_up_to'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'port' => 'Port',
            'pick_up_from' => 'Pick Up From',
            'pick_up_to' => 'Pick Up To',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoads()
    {
        return $this->hasMany(\common\models\Load::className(), ['port_id' => 'id']);
    }




}
