<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "liststate".
 *
 * @property string $state_code
 * @property string $state
 * @property string $aliasModel
 */
abstract class State extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'state';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['state_code', 'state'], 'required'],
            [['state_code'], 'string', 'max' => 2],
            [['state'], 'string', 'max' => 255],
            [['state_code'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'state_code' => 'State Code',
            'state' => 'State',
        ];
    }




}
