<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\controllers\base;

use common\models\State;
use yii\web\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;

/**
* PoststateController implements the CRUD actions for Liststate model.
*/
class StateController extends Controller
{


/**
* @var boolean whether to enable CSRF validation for the actions in this controller.
* CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
*/
public $enableCsrfValidation = false;


/**
* Lists all Liststate models.
* @return mixed
*/
public function actionIndex()
{
    $dataProvider = new \yii\data\ActiveDataProvider([
    'query' => State::find(),
    ]);

Tabs::clearLocalStorage();

Url::remember();
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->render('index', [
'dataProvider' => $dataProvider,
]);
}

/**
* Displays a single Liststate model.
* @param string $state_code
*
* @return mixed
*/
public function actionView($state_code)
{
\Yii::$app->session['__crudReturnUrl'] = Url::previous();
Url::remember();
Tabs::rememberActiveState();

return $this->render('view', [
'model' => $this->findModel($state_code),
]);
}

/**
* Creates a new Liststate model.
* If creation is successful, the browser will be redirected to the 'view' page.
* @return mixed
*/
public function actionCreate()
{
$model = new State;

try {
if ($model->load($_POST) && $model->save()) {
return $this->redirect(['view', 'state_code' => $model->state_code]);
} elseif (!\Yii::$app->request->isPost) {
$model->load($_GET);
}
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
$model->addError('_exception', $msg);
}
return $this->render('create', ['model' => $model]);
}

/**
* Updates an existing Liststate model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param string $state_code
* @return mixed
*/
public function actionUpdate($state_code)
{
$model = $this->findModel($state_code);

if ($model->load($_POST) && $model->save()) {
return $this->redirect(Url::previous());
} else {
return $this->render('update', [
'model' => $model,
]);
}
}

/**
* Deletes an existing Liststate model.
* If deletion is successful, the browser will be redirected to the 'index' page.
* @param string $state_code
* @return mixed
*/
public function actionDelete($state_code)
{
try {
$this->findModel($state_code)->delete();
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
\Yii::$app->getSession()->addFlash('error', $msg);
return $this->redirect(Url::previous());
}

// TODO: improve detection
$isPivot = strstr('$state_code',',');
if ($isPivot == true) {
return $this->redirect(Url::previous());
} elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
Url::remember(null);
$url = \Yii::$app->session['__crudReturnUrl'];
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->redirect($url);
} else {
return $this->redirect(['index']);
}
}

/**
* Finds the Liststate model based on its primary key value.
* If the model is not found, a 404 HTTP exception will be thrown.
* @param string $state_code
* @return State the loaded model
* @throws HttpException if the model cannot be found
*/
protected function findModel($state_code)
{
if (($model = State::findOne($state_code)) !== null) {
return $model;
} else {
throw new HttpException(404, 'The requested page does not exist.');
}
}
}
